-- =============================================================================
-- SEED OK CAPSULE PRODUCTS
-- =============================================================================
-- This migration seeds the database with the 56 products from the OK Capsule catalog.

INSERT INTO public.products (supplement_name, brand, product_name, product_url, price) VALUES
('Glutamine', 'OK Capsule', 'OK Capsule L-Glutamine', 'https://ok-capsule.com/products/l-glutamine', 22.00),
('Citrulline', 'OK Capsule', 'OK Capsule L-Citrulline', 'https://ok-capsule.com/products/l-citrulline', 24.00),
('Tyrosine', 'OK Capsule', 'OK Capsule L-Tyrosine', 'https://ok-capsule.com/products/l-tyrosine', 19.00),
('Arginine', 'OK Capsule', 'OK Capsule L-Arginine', 'https://ok-capsule.com/products/l-arginine', 21.00),
('Carnitine', 'OK Capsule', 'OK Capsule L-Carnitine', 'https://ok-capsule.com/products/l-carnitine', 28.00),
('Theanine', 'OK Capsule', 'OK Capsule L-Theanine', 'https://ok-capsule.com/products/l-theanine', 23.00),
('BCAA', 'OK Capsule', 'OK Capsule BCAA 2:1:1', 'https://ok-capsule.com/products/bcaa', 35.00),
('Resveratrol', 'OK Capsule', 'OK Capsule Trans-Resveratrol', 'https://ok-capsule.com/products/resveratrol', 42.00),
('Alpha Lipoic Acid', 'OK Capsule', 'OK Capsule Alpha Lipoic Acid', 'https://ok-capsule.com/products/alpha-lipoic-acid', 33.00),
('Quercetin', 'OK Capsule', 'OK Capsule Quercetin', 'https://ok-capsule.com/products/quercetin', 29.00),
('CoQ10', 'OK Capsule', 'OK Capsule CoQ10', 'https://ok-capsule.com/products/coq10', 45.00),
('NAC', 'OK Capsule', 'OK Capsule N-Acetylcysteine', 'https://ok-capsule.com/products/nac', 26.00),
('Omega 3', 'OK Capsule', 'OK Capsule Omega-3 Fish Oil', 'https://ok-capsule.com/products/omega-3', 38.00),
('Ginger Root', 'OK Capsule', 'OK Capsule Ginger Root Extract', 'https://ok-capsule.com/products/ginger-root', 18.00),
('Cordyceps', 'OK Capsule', 'OK Capsule Cordyceps Mushroom', 'https://ok-capsule.com/products/cordyceps', 34.00),
('Ashwagandha', 'OK Capsule', 'OK Capsule Ashwagandha Root', 'https://ok-capsule.com/products/ashwagandha', 25.00),
('Berberine', 'OK Capsule', 'OK Capsule Berberine HCl', 'https://ok-capsule.com/products/berberine-hcl', 39.00),
('Green Coffee Extract', 'OK Capsule', 'OK Capsule Green Coffee Bean Extract', 'https://ok-capsule.com/products/green-coffee-extract', 27.00),
('Fenugreek', 'OK Capsule', 'OK Capsule Fenugreek Seed', 'https://ok-capsule.com/products/fenugreek', 17.00),
('Elderberry', 'OK Capsule', 'OK Capsule Elderberry Extract', 'https://ok-capsule.com/products/elderberry', 28.00),
('Green Tea Extract', 'OK Capsule', 'OK Capsule Green Tea Extract', 'https://ok-capsule.com/products/green-tea-extract', 24.00),
('Mushroom Immune', 'OK Capsule', 'OK Capsule Mushroom Immune Blend', 'https://ok-capsule.com/products/mushroom-immune', 40.00),
('Forslean', 'OK Capsule', 'OK Capsule Forslean (Coleus Forskohlii)', 'https://ok-capsule.com/products/forslean', 36.00),
('Triphala', 'OK Capsule', 'OK Capsule Triphala', 'https://ok-capsule.com/products/triphala', 20.00),
('Soothing Fiber', 'OK Capsule', 'OK Capsule Soothing Fiber Blend', 'https://ok-capsule.com/products/soothing-fiber', 30.00),
('Tribulus', 'OK Capsule', 'OK Capsule Tribulus Terrestris', 'https://ok-capsule.com/products/tribulus', 22.00),
('Lion''s Mane', 'OK Capsule', 'OK Capsule Lion''s Mane Mushroom', 'https://ok-capsule.com/products/lions-mane', 35.00),
('Milk Thistle', 'OK Capsule', 'OK Capsule Milk Thistle Extract', 'https://ok-capsule.com/products/milk-thistle', 26.00),
('Herbal Sleep Blend', 'OK Capsule', 'OK Capsule Herbal Sleep Blend', 'https://ok-capsule.com/products/herbal-sleep-blend', 32.00),
('Rhodiola', 'OK Capsule', 'OK Capsule Rhodiola Rosea', 'https://ok-capsule.com/products/rhodiola', 29.00),
('Berberine', 'OK Capsule', 'OK Capsule Berberine Complex', 'https://ok-capsule.com/products/berberine-complex', 41.00),
('Big Libido', 'OK Capsule', 'OK Capsule Big Libido Formula', 'https://ok-capsule.com/products/big-libido', 45.00),
('Trace Minerals', 'OK Capsule', 'OK Capsule Trace Minerals Complex', 'https://ok-capsule.com/products/trace-minerals', 22.00),
('Easy Iron', 'OK Capsule', 'OK Capsule Easy Iron (Bisglycinate)', 'https://ok-capsule.com/products/easy-iron', 20.00),
('Chromium', 'OK Capsule', 'OK Capsule Chromium Picolinate', 'https://ok-capsule.com/products/chromium-picolinate', 15.00),
('Calcium Citrate', 'OK Capsule', 'OK Capsule Calcium Citrate', 'https://ok-capsule.com/products/calcium-citrate', 18.00),
('Magnesium', 'OK Capsule', 'OK Capsule Magnesium Glycinate', 'https://ok-capsule.com/products/magnesium-glycinate', 28.00),
('Boron', 'OK Capsule', 'OK Capsule Boron', 'https://ok-capsule.com/products/boron', 14.00),
('Chromium', 'OK Capsule', 'OK Capsule GTF Chromium', 'https://ok-capsule.com/products/gtf-chromium', 16.00),
('Zinc', 'OK Capsule', 'OK Capsule Zinc Picolinate', 'https://ok-capsule.com/products/zinc', 15.00),
('Complete Probiotic', 'OK Capsule', 'OK Capsule Complete Probiotic 50B', 'https://ok-capsule.com/products/complete-probiotic', 48.00),
('Melatonin', 'OK Capsule', 'OK Capsule Melatonin 3mg', 'https://ok-capsule.com/products/melatonin', 12.00),
('Creatine', 'OK Capsule', 'OK Capsule Creatine Monohydrate', 'https://ok-capsule.com/products/creatine', 25.00),
('Hyaluronic Acid', 'OK Capsule', 'OK Capsule Hyaluronic Acid', 'https://ok-capsule.com/products/hyaluronic-acid', 33.00),
('NR', 'OK Capsule', 'OK Capsule Nicotinamide Riboside (NR)', 'https://ok-capsule.com/products/nr', 55.00),
('DIM', 'OK Capsule', 'OK Capsule DIM (Diindolylmethane)', 'https://ok-capsule.com/products/dim', 31.00),
('Vegan Glucosamine', 'OK Capsule', 'OK Capsule Vegan Glucosamine HCl', 'https://ok-capsule.com/products/vegan-glucosamine', 29.00),
('Turmeric', 'OK Capsule', 'OK Capsule Turmeric Curcumin', 'https://ok-capsule.com/products/turmeric', 27.00),
('Melatonin SR', 'OK Capsule', 'OK Capsule Melatonin SR (Sustained Release)', 'https://ok-capsule.com/products/melatonin-sr', 18.00),
('DHEA', 'OK Capsule', 'OK Capsule DHEA', 'https://ok-capsule.com/products/dhea', 21.00),
('Vitamin D', 'OK Capsule', 'OK Capsule Vitamin D3 5000IU', 'https://ok-capsule.com/products/vitamin-d', 16.00),
('D Complex', 'OK Capsule', 'OK Capsule Vitamin D3+K2 Complex', 'https://ok-capsule.com/products/d-complex', 24.00),
('Vitamin B12', 'OK Capsule', 'OK Capsule Vitamin B12 (Methylcobalamin)', 'https://ok-capsule.com/products/vitamin-b12', 19.00),
('Vitamin C', 'OK Capsule', 'OK Capsule Vitamin C with Bioflavonoids', 'https://ok-capsule.com/products/vitamin-c', 20.00),
('Biotin', 'OK Capsule', 'OK Capsule Biotin 10,000mcg', 'https://ok-capsule.com/products/biotin', 17.00),
('Methyl B-Complex', 'OK Capsule', 'OK Capsule Methyl B-Complex', 'https://ok-capsule.com/products/methyl-b-complex', 30.00)
ON CONFLICT DO NOTHING; 